# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Phylanx - A Distributed Array Toolkit
email: phylanx@stellar-group.org
author: STEllAR Group
# Phylanx is a distributed mathematics library front-end with an HPX backend and C++ and Python front-ends
description: > # this means to ignore newlines until "baseurl:"
  This material is based upon work supported by the National Science Foundation under Grant No. 1737785.
  Any opinions, findings, and conclusions or recommendations expressed in this material are those of the
  author(s) and do not necessarily reflect the views of the National Science Foundation.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fns.prs.am" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
irc_channel: ste||ar
irc_server: freenode.net
github_username:  STEllAR-GROUP/phylanx

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
sass:
  sass_dir: ./_sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
